version: '3.8'

services:
  redis:
    image: redis
    restart: always
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
  worker:
    restart: always
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    command: celery -A django_project worker -l INFO
volumes:
  postgres_volume: