# Generated by Django 4.1.3 on 2022-12-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_qticketssalesinfo_author_targetinfo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qticketssalesinfo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='targetinfo',
            name='author',
        ),
    ]
