# Generated by Django 4.1.3 on 2022-12-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_qticketssalesinfo_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='spreadSheetPositon',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Позиция в гугл таблице'),
        ),
    ]
