# Generated by Django 4.1.3 on 2022-12-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_concert_spreadsheetpositon'),
    ]

    operations = [
        migrations.AddField(
            model_name='qticketssalesinfo',
            name='spreadSheetTargetPosition',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер подключенного аккаунта'),
        ),
        migrations.AddField(
            model_name='targetinfo',
            name='spreadSheetQticketsPosition',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер подключенного аккаунта'),
        ),
    ]
