# Generated by Django 4.1.3 on 2022-12-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_qticketssalesinfo_spreadsheettargetposition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qticketssalesinfo',
            old_name='spreadSheetTargetPosition',
            new_name='spreadSheetQticketsPosition',
        ),
        migrations.RenameField(
            model_name='targetinfo',
            old_name='spreadSheetQticketsPosition',
            new_name='spreadSheetTargetPosition',
        ),
    ]
